### ISSUE TITLE
Test 1

### ISSUE THREAD

**Issue by SFTCP1** [SFTCP1/bots-collection#1]
stale up

**Comment by mope-io-nw** [comment]
Hmmm i think you should have more bots

**Comment by SFTCP1** [comment]
@LogoEditingMaster should have stale but we don't

**Comment by mope-io-nw** [comment]
![FeatureToastSFTCP1](https://user-images.githubusercontent.com/69103980/119821565-ffecbc80-bef2-11eb-970c-635455188a93.gif)

this toast is so perfetto

**Comment by mope-io-nw** [comment]
@LogoEditingMaster
@SFTCP1
@SFTCP2
@mope-io-nw
@Kraken175
@zacharytanor
@bdb391a
@Deepbabies
@notsodeepbabies

**Comment by mope-io-nw** [comment]
Great job dude you have called stale

**Comment by SFTCP1** [comment]
Could i just tame myself?

**Comment by SFTCP2** [comment]
auuuuuuu!

**Comment by SFTCP1** [comment]
Reopening

**Comment by kraken175** [comment]
You have been watching this for a while

**Comment by SFTCP1** [comment]
We have updated the limit for bots

**Comment by mope-io-nw** [comment]
Get off stale please

**Comment by mope-io-nw** [comment]
Please don't come back

**Comment by mope-io-nw** [comment]
no!

**Comment by mope-io-nw** [comment]
STOP DOING THIS YOU EDITOR PUT THAT YOU!!

Just remove .github/stale.yml and stop adding those files or else it cames back again!

**Comment by SFTCP1** [comment]
Ok we have to turn off the thing because it annoys me for nothing

**Comment by SFTCP1** [comment]
We won't but we added the issue-label-bot that's getting too hard

**Comment by mope-io-nw** [comment]
Fine, we will delete it

**Comment by mope-io-nw** [comment]
HOW COULD YOU DO THIS???

Because you try to add stale.yml to make the answers sleepy

**Comment by mope-io-nw** [comment]
please remove stale.yml immediately

**Comment by SFTCP1** [comment]
Now removed.

**Comment by mope-io-nw** [comment]
Ok thanks! now close this
